# question: 問題, type: 四則演算の種類, formula: 計算式, answer: 答え
# type: 1.足し算, 2.引き算, 3.掛け算, 4.割り算, 5.その他

- question: 子供が5人います。新しく4人来ました。子供は全員で何人になりましたか？
  type: 1
  formula: 5+4
  answer: 9

- question: あめが8個あります。5個食べたら、何個残っていますか？
  type: 2
  formula: 8-5
  answer: 4

- question: クッキーが8個ずつ入った箱が4つあります。クッキーは全部で何個ありますか？
  type: 3
  formula: 8*4
  answer: 32

- question: 折り紙が40枚あります。1人に8枚ずつ配ると何人に分けられますか？
  type: 4
  formula: 40/8
  answer: 5
